### ISSUE TITLE
Is it still working?

### ISSUE THREAD

**Issue by LonnyX** [demeyerthom/belgian-companies#1]
Hello,

Thank you for open sourcing this, It's a very interesting idea.
I wonder if it's still working and up to date? Is it possible to parse and store data in a database?

**Comment by demeyerthom** [comment]
Hi Lonny, I think it was working for the fetching and parsing of publications, and the fetching of company pages. I was still working on the parsing of those. However, IIR the publication pages have also changed format, so I would not be surprised if that is also broken.

The data gets stored in Kafka in json format. You could hang on an extra application to parse the data to a database from a topic, but currently it does not store it anywhere else. I was considering using something like kafka connect to send it to a Mongo db, but never came around to it.

Also, i am not planning on working on this in the future, so no updates are forthcoming. But feel free to fork this and continue working on it!
